### ISSUE TITLE
5-1 yaml gives error

### ISSUE THREAD

**Issue by jjdorak** [kubernetes-up-and-running/examples#11]
When trying to deploy the 5-1 example yaml:
$ kubectl apply -f kuard-pod.yaml 
error: error validating "kuard-pod.yaml": error validating data: ValidationError(Pod.metadata): unknown field "spec" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta; if you choose to ignore these errors, turn validation off with --validate=false

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

Update: Example 5-2 worked ok.
Also updated error message to correct one

-jjd

**Comment by NillsF** [comment]
It's been a while since you opened this issue. I had the same issue, and I created a full request with the solution: https://github.com/kubernetes-up-and-running/examples/pull/13 

Please check if the updated code helps you out.

**Comment by jjdorak** [comment]
Thanks, I did finallly notice that.  The book was a great help.
