### ISSUE TITLE
Examples of lessons 2-4

### ISSUE THREAD

**Issue by sorrigit** [kubernetes-up-and-running/examples#19]
Why does examples start from chapter when examples are available starting from chapter 2 in the book? And why are examples separate from guard repository anyway? The book has a chaotic structure and so the examples. It takes a while to get an overview and what to do first.

**Comment by lachie83** [comment]
We appreciate the feedback and apologize for the confusion it creates. We will continue to see if we can improve the structure to make it more straightforward to follow
