### ISSUE TITLE
--replicas flag has been deprecated

### ISSUE THREAD

**Issue by IAmATeaPot418** [kubernetes-up-and-running/examples#23]
Commands in chapter 8 rely on the depreciated replicas. This is several places throughout the book. 

It was removed in 1.18.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#deprecation-4

kubectl run be-default \
>   --image=gcr.io/kuar-demo/kuard-amd64:blue \
>   --replicas=3 \
>   --port=8080
Flag --replicas has been deprecated, has no effect and will be removed in the future.
pod/be-default created

**Comment by SergiyKolesnikov** [comment]
The closest alternative I could come up with for a command such as
```
kubectl run alpaca-prod --image=gcr.io/kuar-demo/kuard-amd64:blue --replicas=3 --port=8080 --labels="ver=1,app=alpaca,env=prod"
```

would be the three commands  

```
kubectl create deployment alpaca-prod --image=gcr.io/kuar-demo/kuard-amd64:blue --replicas=3 --port=8080
```
```
kubectl label --overwrite deployments ver=1 app=alpaca env=prod --selector="app=alpaca-prod"
```
```
kubectl label --overwrite pods ver=1 app=alpaca env=prod --selector="app=alpaca-prod"
```
So, basically, the labels for the resources (the deployment and pods) have to be specified in separate commands.

**Comment by lachie83** [comment]
Thank you for raising this issue. We've updated this in the 3rd edition to something similar to the following

```
# First, create the deployment
$ kubectl create deployment alpaca-prod --image=[gcr.io/kuar-demo/kuard-amd64:blue](http://gcr.io/kuar-demo/kuard-amd64:blue) --replicas=2
# After the deployment is created, you can add some labels
$ kubectl label deployments alpaca-prod --overwrite ver=1 app=alpaca env=prod
```
