### ISSUE TITLE
I have book 3rd edition will these examples work? they say last update 5 years ago

### ISSUE THREAD

**Issue by CarlosJoseChaconChavarria** [kubernetes-up-and-running/examples#25]
hi guys

I have book 3rd edition will these examples work? they say last update 5 years ago

of there is a more recent repo?

thanks

**Comment by Adeniyikayodee** [comment]
no response... wow

**Comment by lachie83** [comment]
Hi @CarlosJoseChaconChavarria apologies for the delay in response. I'm one of the 3rd edition co-authors and am working on getting these examples updated to align with the 3rd edition.

**Comment by lachie83** [comment]
As a first step, I've updated the manifests to reflect current APIs from the 1st edition content. I plan to tag the repo with the 1st edition content before updating for 3rd content.

**Comment by lachie83** [comment]
https://github.com/kubernetes-up-and-running/examples/pull/29 is the update to 3rd edition
