### ISSUE TITLE
13-2yaml can not work 

### ISSUE THREAD

**Issue by jacksunsong** [kubernetes-up-and-running/examples#9]
kubectl create -f 13-2.yaml 
13-2 yaml is writed as

kind: Service
apiVersion: v1
metadata:
  name: external-ip-database
I get the error 

The Service "external-ip-database" is invalid: spec.ports: Required value

**Comment by lachie83** [comment]
Thank you very much for reporting this. This issue has been addressed in https://github.com/kubernetes-up-and-running/examples/pull/28
